sudo: false
language: go
go:
  - "1.8"

before_install:
  - go install -race std
  - go get golang.org/x/tools/cmd/cover

script:
  - go test -v -race ./cmd/... ./controllers/... ./market/... ./middleware/... ./platforms/...
  - go test -v -cover ./cmd/... ./controllers/... ./market/... ./middleware/... ./platforms/...
