sudo: false
dist: trusty
language: go
go:
  - "1.11"
cache:
  directories:
    - $GO_PATH/pkg/mod
services:
  - docker
before_install:
  # go std library refresh
  - go install -race std

  # - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s v1.5
script:
  # - golangci-lint run --enable-all --disable=gas
  - make test
  - make build
  - docker build -t registry.heroku.com/bubble-srv-dev/web -t registry.heroku.com/bubble-srv/web .
  - docker login -u="_" -p="$HEROKU_API_KEY" registry.heroku.com
  - docker push registry.heroku.com/bubble-srv-dev/web
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker push registry.heroku.com/bubble-srv/web;
    fi
  # release should be done by hands https://devcenter.heroku.com/changelog-items/1426
  # heroku container:release web worker --app bubble-srv-dev
after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.out
notifications:
  email: false
