sudo: false
language: go
go:
  - "1.8"
cache:
  directories:
    - vendor
before_install:
  - go install -race std
  - go get golang.org/x/tools/cmd/cover
  - go get -t -v ./... # TODO remove when write unit tests and mock dependency
script:
  - make test
after_success:
  - $HOME/gopath/bin/goveralls -service=travis-ci
