sudo: required
language: go
go:
  - "1.8"
services:
  - docker
before_install:
  # go std library refresh
  - go install -race std

  # go coverage to coverals by goverals
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

  - go get github.com/kardianos/govendor
  - make deps
script:
  - make test
  - make build
after_success:
  - $HOME/gopath/bin/goveralls -ignore=cmd/server/main.go -service=travis-ci -repotoken $COVERALLS_TOKEN
  - docker build --file Dockerfile.prod .
