sudo: false
dist: trusty
language: go
go:
  - "1.12"
cache:
  directories:
    # - $GO_PATH/pkg/mod
    - /home/travis/gopath/pkg/mod
    # - $GOCACHE
    - /home/travis/.cache/go-build
services:
  - docker
script:
  - make test
  - make build
  - docker build -t registry.heroku.com/bubble-srv-dev/web -t registry.heroku.com/bubble-srv/web .
  - echo "$HEROKU_API_KEY" | docker login -u="_" --password-stdin registry.heroku.com
  - docker push registry.heroku.com/bubble-srv-dev/web
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker push registry.heroku.com/bubble-srv/web;
    fi
  # release should be done by hands https://devcenter.heroku.com/changelog-items/1426
  # heroku container:release web worker --app bubble-srv-dev
after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.out
notifications:
  email: false
