sudo: false
language: go
go:
  - "1.8"
cache:
  directories:
    - vendor
before_install:
  - go install -race std
  - go get -u github.com/kardianos/govendor
  - govendor sync
  - go get github.com/mattn/goveralls
script:
  - make test
after_success:
  - $HOME/gopath/bin/goveralls -ignore=cmd/server/main.go -service=travis-ci
