sudo: false
language: go
go:
  - "1.7"
  - tip

services:
  - redis-server

before_install:
  - go install -race std
  - go get golang.org/x/tools/cmd/cover

script:
  - go test -v -race ./cmd/...
  - go test -v -cover ./cmd/...

matrix:
  allow_failures:
    - go: tip
