sudo: false
dist: trusty
language: go
go:
  - "1.10"
cache:
  directories:
    - $GO_PATH/src/v
services:
  - docker
before_install:
  # go std library refresh
  - go install -race std

  - go get github.com/mattn/goveralls # upload coverage
  - go get golang.org/x/vgo
script:
  - make test
  - make build
  - docker build -t registry.heroku.com/bubble-srv-dev/web -t registry.heroku.com/bubble-srv/web .
  - docker login -u="$HEROKU_USERNAME" -p="$HEROKU_API_KEY" registry.heroku.com
  - docker push registry.heroku.com/bubble-srv-dev/web
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker push registry.heroku.com/bubble-srv/web;
    fi
after_success:
  - $HOME/gopath/bin/goveralls -coverprofile coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
notifications:
  email: false
