sudo: false
language: go
go:
  - "1.8"

before_install:
  - go install -race std
  - go get golang.org/x/tools/cmd/cover
  - go get -t -v ./... # TODO remove when write unit tests and interface dependency

script:
  - make test
