sudo: false
language: go
go:
  - "1.8"

services:
  - mongodb

before_script:
  - sleep 15 # https://docs.travis-ci.com/user/database-setup/#MongoDB-does-not-immediately-accept-connections
  - mongo mydb_test --eval 'db.addUser("travis", "test");'

before_install:
  - go install -race std
#  - go get golang.org/x/tools/cmd/cover

script:
  - go test -v -race ./cmd/...
#  - go test -v -cover ./cmd/...
