FROM golang:1.8-alpine AS build-env
ADD . /go/src/github.com/server-may-cry/bubble-go
WORKDIR /go/src/github.com/server-may-cry/bubble-go
RUN apk update && apk upgrade && \
    apk add --no-cache git openssl make && \
    go get -u github.com/golang/dep/cmd/dep && \
    make deps && \
    make build

FROM scratch
COPY --from=build-env /go/src/github.com/server-may-cry/bubble-go/server .
COPY --from=build-env /go/src/github.com/server-may-cry/bubble-go/config ./config
CMD ["server"]
