version: '2'
services:
  go:
    build:
      context: .
      dockerfile: Dockerfile.dev.Dockerfile
    working_dir: /go/src/github.com/server-may-cry/bubble-go
    environment:
      DB_URL: postgres://docker:docker@db.local:5432/docker
      PORT: 8080
    volumes:
      - .:/go/src/github.com/server-may-cry/bubble-go
      - ./.netrc:/root/.netrc:ro
      - vgo:/go/src/v
    links:
      - postgres:db.local
    ports:
      - "8080:8080"
    command: ["sh"]
  postgres:
    image: postgres:9.6-alpine
    expose:
      - "5432/TCP"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
    volumes:
      - db:/var/lib/postgresql
volumes:
  db: ~
  vgo: ~
