version: '2'
services:
  go:
    image: scratch
    environment:
      DB_URL: postgres://docker:docker@db.local:5432/docker
      PORT: 8080
    volumes:
      - ./bubble-go:/app/bubble-go:ro
      - ./config:/app/config:ro
    links:
      - postgres:db.local
    ports:
      - "8080:8080"
    command: ["/app/bubble-go"]
  postgres:
    image: postgres:9.6-alpine
    expose:
      - "5432/TCP"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
    volumes:
      - db:/var/lib/postgresql
volumes:
  db: ~
