version: '2'
services:
  go:
    build: .
    environment:
      HEROKU_POSTGRESQL_SILVER_URL: http://docker:docker@db.local:5432/docker
      PORT: 8080
    volumes:
      - ./bubble-go:/app/bubble-go:ro
      - ./config:/app/config:ro
    links:
      - postgres:db.local
    ports:
      - "8080:8080"
  postgres:
    image: postgres:10.4-alpine
    expose:
      - "5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
    volumes:
      - db:/var/lib/postgresql
volumes:
  db: ~
