version: '2'
services:
  go:
    build: .
    working_dir: /go/src/github.com/server-may-cry/bubble-go
    environment:
      - DB_URL=postgres://docker:docker@db.local:5432/docker
      - PORT=80
    volumes:
      - .:/go/src/github.com/server-may-cry/bubble-go
    links:
      - postgres:db.local
    ports:
      - 80:80
    command: make all
  postgres:
    image: postgres:9.6-alpine
    expose:
      - 5432/TCP
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker
    volumes:
      - db:/var/lib/postgresql
volumes:
  db: {}
